# http://lint.travis-ci.org/

language: php

php:
  - 7.0

sudo: false

branches:
    only:
        - master
        - php7
        - /^\d+\.\d+\.\d+$/

before_script:
  - composer install --dev

script: composer test

# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - rh+github@hrdns.de
  on_success: never
  on_failure: change
