language: php

php:
  - 5.5
  - 5.6

sudo: false

before_script:
  - composer install --dev

script: composer test

# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - rh+github@hrdns.de
  on_success: never
  on_failure: change

# http://lint.travis-ci.org/